# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8882
    servlet:
      context-path: /aidog

# mysql
spring:
    profiles:
      active: dev
    # 指定静态资源的路径
    resources:
      static-locations: classpath:/adminlte/,classpath:/bootstrap/
    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true

    devtools:
        restart:
            enabled: true #是否支持热部署
        redis:
            database: 2 #索引（默认为0）
            host: 112.122.252.45 #地址
            port: 6379 #端口号
            password: 123456 #连接密码（默认空）
            jedis:
              pool:
                max-idle: 8 #连接池中的最大空闲连接
                min-idle: 0 #连接池中的最小空闲连接
                max-active: 8 #连接池最大连接数（使用负值表示没有限制）
                max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
            #sentinel:
              #master: mymaster # 哨兵监听的Redis server的名称
              #nodes:
              #127.0.0.1:26379,127.0.0.1:26479,127.0.0.1:26579 #哨兵的配置列表
            timeout: 2000 #连接超时时间（毫秒）
    data:
      mongodb:
        uri: mongodb://wang:123456@122.112.252.45:27017/aidog


mybatis:
  mapperLocations: classpath:mapper/*.xml